name: Publish to NPM

# publish only when package json has changed - assuming version upgrade
on:
  push:
    branches: [main]
    paths: "lib/nthul/package.json"

jobs:
  publish:
    if: github.event.repository.owner.login == 'react18-tools'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write

    defaults:
      run:
        working-directory: ./lib/nthul

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
        # fail and not publish if any of the unit tests are failing
      - name: Test
        run: pnpm test
      - name: Create release and publish to NPM
        run: pnpm build && pnpm publish-package && node scope.js && pnpm publish-package
        # continue on error to publish scoped package name <- by default repo is setup for a non-scoped + scoped package name
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}

      - name: Publish package with long name for better SEO
        continue-on-error: true
        run: |
          cd dist
          sed -i -e "s/.*name.*/\t\"name\": \"nextjs-themes-ultra\",/" package.json
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Publish lite version
      - run: node lite.js && pnpm build && pnpm publish-package && node scope.js && pnpm publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish package with long name for better SEO
        continue-on-error: true
        run: |
          cd dist
          sed -i -e "s/.*name.*/\t\"name\": \"nextjs-themes-ultralite\",/" package.json
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Mark scoped package as deprecated
        run: |
          npm deprecate @mayank1513/nthul "Please use <https://www.npmjs.com/package/nathul> instead. We initially created scoped packages to have similarities with the GitHub Public Repository (which requires packages to be scoped). We are no longer using GPR and thus deprecating all scoped packages for which corresponding un-scoped packages exist."
          npm deprecate @mayank1513/nthul-lite "Please use <https://www.npmjs.com/package/nthul-lite> instead. We initially created scoped packages to have similarities with the GitHub Public Repository (which requires packages to be scoped). We are no longer using GPR and thus deprecating all scoped packages for which corresponding un-scoped packages exist."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
